### ISSUE TITLE
Failed on large-ish file

### ISSUE THREAD

**Issue by hyeongyun0916** [hyeongyun0916/GZIP_Decompressor#3]
Failed on large-ish file

**Comment by PerFlodinVolvo** [comment]
Me too. Trying a few files, the unpacked size stays suspiciously close to 16 KiB.

**Comment by csghone** [comment]
@hyeongyun0916 - Seems like you have fixed this one. Could you please push the fix to the VS Code Marketplace ?

**Comment by hyeongyun0916** [comment]
@csghone Sorry for late. I fixed this issue and published it to v1.2.0.
Thank you for using :)
